// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameFileIndex = "file_indices"

// FileIndex mapped from table <file_indices>
type FileIndex struct {
	ParentID string `gorm:"column:parent_id;primaryKey" json:"parent_id"`
	ChildID  string `gorm:"column:child_id;primaryKey" json:"child_id"`
}

// TableName FileIndex's table name
func (*FileIndex) TableName() string {
	return TableNameFileIndex
}
