// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameFileIndex = "file_indices"

// FileIndex mapped from table <file_indices>
type FileIndex struct {
	ID         string    `gorm:"column:id;primaryKey" json:"id"`
	ParentID   string    `gorm:"column:parent_id;not null" json:"parent_id"`
	ChildID    string    `gorm:"column:child_id;not null" json:"child_id"`
	CreateTime time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP" json:"create_time"`
	UpdateTime time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP" json:"update_time"`
}

// TableName FileIndex's table name
func (*FileIndex) TableName() string {
	return TableNameFileIndex
}
