// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUserNamespace = "user_namespaces"

// UserNamespace mapped from table <user_namespaces>
type UserNamespace struct {
	UserID      int64     `gorm:"column:user_id;primaryKey" json:"user_id"`
	NamespaceID int64     `gorm:"column:namespace_id;primaryKey" json:"namespace_id"`
	Authority   int32     `gorm:"column:authority;not null" json:"authority"`
	CreateTime  time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP" json:"create_time"`
	UpdateTime  time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP" json:"update_time"`
}

// TableName UserNamespace's table name
func (*UserNamespace) TableName() string {
	return TableNameUserNamespace
}
