// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dal

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q             = new(Query)
	FileIndex     *fileIndex
	FileItem      *fileItem
	Namespace     *namespace
	UserNamespace *userNamespace
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	FileIndex = &Q.FileIndex
	FileItem = &Q.FileItem
	Namespace = &Q.Namespace
	UserNamespace = &Q.UserNamespace
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:            db,
		FileIndex:     newFileIndex(db, opts...),
		FileItem:      newFileItem(db, opts...),
		Namespace:     newNamespace(db, opts...),
		UserNamespace: newUserNamespace(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	FileIndex     fileIndex
	FileItem      fileItem
	Namespace     namespace
	UserNamespace userNamespace
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:            db,
		FileIndex:     q.FileIndex.clone(db),
		FileItem:      q.FileItem.clone(db),
		Namespace:     q.Namespace.clone(db),
		UserNamespace: q.UserNamespace.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:            db,
		FileIndex:     q.FileIndex.replaceDB(db),
		FileItem:      q.FileItem.replaceDB(db),
		Namespace:     q.Namespace.replaceDB(db),
		UserNamespace: q.UserNamespace.replaceDB(db),
	}
}

type queryCtx struct {
	FileIndex     IFileIndexDo
	FileItem      IFileItemDo
	Namespace     INamespaceDo
	UserNamespace IUserNamespaceDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		FileIndex:     q.FileIndex.WithContext(ctx),
		FileItem:      q.FileItem.WithContext(ctx),
		Namespace:     q.Namespace.WithContext(ctx),
		UserNamespace: q.UserNamespace.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
