// Code generated by hertz generator.

package file

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	file "github.com/yanguiyuan/cloudspace/biz/model/api/file"
)

// Query .
// @router /files [GET]
func Query(ctx context.Context, c *app.RequestContext) {
	var err error
	var req file.QueryReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(file.QueryResp)

	c.JSON(consts.StatusOK, resp)
}
