// Code generated by Kitex v0.6.1. DO NOT EDIT.

package cloudfileservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	rpc "github.com/yanguiyuan/cloudspace/pkg/rpc"
)

func serviceInfo() *kitex.ServiceInfo {
	return cloudFileServiceServiceInfo
}

var cloudFileServiceServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "CloudFileService"
	handlerType := (*rpc.CloudFileService)(nil)
	methods := map[string]kitex.MethodInfo{
		"add":             kitex.NewMethodInfo(addHandler, newCloudFileServiceAddArgs, newCloudFileServiceAddResult, false),
		"createDirectory": kitex.NewMethodInfo(createDirectoryHandler, newCloudFileServiceCreateDirectoryArgs, newCloudFileServiceCreateDirectoryResult, false),
		"remove":          kitex.NewMethodInfo(removeHandler, newCloudFileServiceRemoveArgs, newCloudFileServiceRemoveResult, false),
		"removeDirectory": kitex.NewMethodInfo(removeDirectoryHandler, newCloudFileServiceRemoveDirectoryArgs, newCloudFileServiceRemoveDirectoryResult, false),
		"query":           kitex.NewMethodInfo(queryHandler, newCloudFileServiceQueryArgs, newCloudFileServiceQueryResult, false),
		"update":          kitex.NewMethodInfo(updateHandler, newCloudFileServiceUpdateArgs, newCloudFileServiceUpdateResult, false),
		"rename":          kitex.NewMethodInfo(renameHandler, newCloudFileServiceRenameArgs, newCloudFileServiceRenameResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "rpc",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.6.1",
		Extra:           extra,
	}
	return svcInfo
}

func addHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*rpc.CloudFileServiceAddArgs)

	err := handler.(rpc.CloudFileService).Add(ctx, realArg.Req)
	if err != nil {
		return err
	}

	return nil
}
func newCloudFileServiceAddArgs() interface{} {
	return rpc.NewCloudFileServiceAddArgs()
}

func newCloudFileServiceAddResult() interface{} {
	return rpc.NewCloudFileServiceAddResult()
}

func createDirectoryHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*rpc.CloudFileServiceCreateDirectoryArgs)

	err := handler.(rpc.CloudFileService).CreateDirectory(ctx, realArg.Req)
	if err != nil {
		return err
	}

	return nil
}
func newCloudFileServiceCreateDirectoryArgs() interface{} {
	return rpc.NewCloudFileServiceCreateDirectoryArgs()
}

func newCloudFileServiceCreateDirectoryResult() interface{} {
	return rpc.NewCloudFileServiceCreateDirectoryResult()
}

func removeHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*rpc.CloudFileServiceRemoveArgs)

	err := handler.(rpc.CloudFileService).Remove(ctx, realArg.Req)
	if err != nil {
		return err
	}

	return nil
}
func newCloudFileServiceRemoveArgs() interface{} {
	return rpc.NewCloudFileServiceRemoveArgs()
}

func newCloudFileServiceRemoveResult() interface{} {
	return rpc.NewCloudFileServiceRemoveResult()
}

func removeDirectoryHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*rpc.CloudFileServiceRemoveDirectoryArgs)

	err := handler.(rpc.CloudFileService).RemoveDirectory(ctx, realArg.Id)
	if err != nil {
		return err
	}

	return nil
}
func newCloudFileServiceRemoveDirectoryArgs() interface{} {
	return rpc.NewCloudFileServiceRemoveDirectoryArgs()
}

func newCloudFileServiceRemoveDirectoryResult() interface{} {
	return rpc.NewCloudFileServiceRemoveDirectoryResult()
}

func queryHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*rpc.CloudFileServiceQueryArgs)
	realResult := result.(*rpc.CloudFileServiceQueryResult)
	success, err := handler.(rpc.CloudFileService).Query(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCloudFileServiceQueryArgs() interface{} {
	return rpc.NewCloudFileServiceQueryArgs()
}

func newCloudFileServiceQueryResult() interface{} {
	return rpc.NewCloudFileServiceQueryResult()
}

func updateHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*rpc.CloudFileServiceUpdateArgs)

	err := handler.(rpc.CloudFileService).Update(ctx, realArg.Req)
	if err != nil {
		return err
	}

	return nil
}
func newCloudFileServiceUpdateArgs() interface{} {
	return rpc.NewCloudFileServiceUpdateArgs()
}

func newCloudFileServiceUpdateResult() interface{} {
	return rpc.NewCloudFileServiceUpdateResult()
}

func renameHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*rpc.CloudFileServiceRenameArgs)

	err := handler.(rpc.CloudFileService).Rename(ctx, realArg.Id, realArg.NewName_)
	if err != nil {
		return err
	}

	return nil
}
func newCloudFileServiceRenameArgs() interface{} {
	return rpc.NewCloudFileServiceRenameArgs()
}

func newCloudFileServiceRenameResult() interface{} {
	return rpc.NewCloudFileServiceRenameResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Add(ctx context.Context, req *rpc.AddRequest) (err error) {
	var _args rpc.CloudFileServiceAddArgs
	_args.Req = req
	var _result rpc.CloudFileServiceAddResult
	if err = p.c.Call(ctx, "add", &_args, &_result); err != nil {
		return
	}
	return nil
}

func (p *kClient) CreateDirectory(ctx context.Context, req *rpc.CreateDirectoryRequest) (err error) {
	var _args rpc.CloudFileServiceCreateDirectoryArgs
	_args.Req = req
	var _result rpc.CloudFileServiceCreateDirectoryResult
	if err = p.c.Call(ctx, "createDirectory", &_args, &_result); err != nil {
		return
	}
	return nil
}

func (p *kClient) Remove(ctx context.Context, req *rpc.RemoveRequest) (err error) {
	var _args rpc.CloudFileServiceRemoveArgs
	_args.Req = req
	var _result rpc.CloudFileServiceRemoveResult
	if err = p.c.Call(ctx, "remove", &_args, &_result); err != nil {
		return
	}
	return nil
}

func (p *kClient) RemoveDirectory(ctx context.Context, id string) (err error) {
	var _args rpc.CloudFileServiceRemoveDirectoryArgs
	_args.Id = id
	var _result rpc.CloudFileServiceRemoveDirectoryResult
	if err = p.c.Call(ctx, "removeDirectory", &_args, &_result); err != nil {
		return
	}
	return nil
}

func (p *kClient) Query(ctx context.Context, req *rpc.QueryRequest) (r *rpc.QueryResponse, err error) {
	var _args rpc.CloudFileServiceQueryArgs
	_args.Req = req
	var _result rpc.CloudFileServiceQueryResult
	if err = p.c.Call(ctx, "query", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Update(ctx context.Context, req *rpc.UpdateRequest) (err error) {
	var _args rpc.CloudFileServiceUpdateArgs
	_args.Req = req
	var _result rpc.CloudFileServiceUpdateResult
	if err = p.c.Call(ctx, "update", &_args, &_result); err != nil {
		return
	}
	return nil
}

func (p *kClient) Rename(ctx context.Context, id string, newName_ string) (err error) {
	var _args rpc.CloudFileServiceRenameArgs
	_args.Id = id
	_args.NewName_ = newName_
	var _result rpc.CloudFileServiceRenameResult
	if err = p.c.Call(ctx, "rename", &_args, &_result); err != nil {
		return
	}
	return nil
}
