CREATE DATABASE IF NOT EXISTS cloud_file;

USE cloud_file;

CREATE TABLE IF NOT EXISTS file_items(
    `id` VARCHAR(12) PRIMARY KEY,
    `name` VARCHAR(255) NOT NULL,
    `type` VARCHAR(20) NOT NULL,
    `create_time` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    `update_time` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL
);


CREATE TABLE IF NOT EXISTS file_indices(
    `id` VARCHAR(12) PRIMARY KEY,
    `parent_id` VARCHAR(12) NOT NULL,
    `child_id` VARCHAR(12) NOT NULL,
    `create_time` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    `update_time` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL
);



INSERT INTO file_items(id, name, type) VALUE ('@root','root','root');