// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AccountManagementDialog: typeof import('./src/components/user/AccountManagementDialog.vue')['default']
    AppTemplate: typeof import('./src/components/AppTemplate.vue')['default']
    CurrentTime: typeof import('./src/components/CurrentTime.vue')['default']
    Drawer: typeof import('./src/components/Drawer.vue')['default']
    FileCreateDialog: typeof import('./src/components/file/FileCreateDialog.vue')['default']
    FileManagementHeader: typeof import('./src/components/file/FileManagementHeader.vue')['default']
    FileUploadDialog: typeof import('./src/components/file/FileUploadDialog.vue')['default']
    MarkdownPreview: typeof import('./src/components/MarkdownPreview.vue')['default']
    NamespaceManagementDialog: typeof import('./src/components/file/NamespaceManagementDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    YButton: typeof import('./src/components/YButton.vue')['default']
    YMaskCard: typeof import('./src/components/YMaskCard.vue')['default']
  }
}
