// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AccountManagementDialog: typeof import('./src/components/user/AccountManagementDialog.vue')['default']
    AcountManagementDialog: typeof import('./src/components/user/AcountManagementDialog.vue')['default']
    AppTemplate: typeof import('./src/components/AppTemplate.vue')['default']
    AppTempleate: typeof import('./src/components/AppTempleate.vue')['default']
    CreateTextFile: typeof import('./src/components/file/CreateTextFile.vue')['default']
    CurrentTime: typeof import('./src/components/CurrentTime.vue')['default']
    Drawer: typeof import('./src/components/Drawer.vue')['default']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    FileCreateDialog: typeof import('./src/components/file/FileCreateDialog.vue')['default']
    FileManagementHeader: typeof import('./src/components/file/FileManagementHeader.vue')['default']
    FileUploadDialog: typeof import('./src/components/file/FileUploadDialog.vue')['default']
    MarkdownEdit: typeof import('./src/components/file/MarkdownEdit.vue')['default']
    MarkdownPreview: typeof import('./src/components/MarkdownPreview.vue')['default']
    NamespaceManagement: typeof import('./src/components/file/NamespaceManagement.vue')['default']
    NamespaceManagementDialog: typeof import('./src/components/file/NamespaceManagementDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    YButton: typeof import('./src/components/YButton.vue')['default']
    YMaskCard: typeof import('./src/components/YMaskCard.vue')['default']
  }
}
